version: '3.1'

volumes:
  prometheus_data: {}
  jenkins_home: {}
  jenkins_data:
    driver: local

networks:
  privnet:
    ipam:
      driver: default
      config:
        - subnet: 172.28.1.0/24

services:

  # PROMETHEUS SERVICE
  prometheus:
    image: "prom/prometheus:v2.1.0"
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - '9090:9090'
    networks:
      privnet:
        ipv4_address: '172.28.1.11'
    restart: always

  # NODE EXPORTER SERVICE
  node-exporter:
    image: "prom/node-exporter"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command: 
      - '--path.procfs=/host/proc' 
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points'
      - '^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)'
    ports:
      - '9100:9100'
    networks:
      privnet:
        ipv4_address: '172.28.1.12'
    restart: on-failure:10

  # JENKINS SERVICE
  jenkins:
    image: "jenkins/jenkins:lts"
    volumes:
      - jenkins_data:/jenkins_config
      - jenkins_home:/var/jenkins_home/:rw
    ports:
      - '8080:8080'
      - '443:8443'
      - '50000:50000'
    networks:
      privnet:
        ipv4_address: '172.28.1.13'
    restart: always

  # JENKINS PYTHON EXPORTER SERVICE
  jenkins-exporter:
    build: ./jenkins_exporter
    image: jenkins_exporter:latest
    volumes:
      - jenkins_home:/var/jenkins_home/:ro
    command: ["-j", "http://172.28.1.13:8080", "-p", "9200", "--user", "admin"]
    ports:
      - '9200:9200'
    networks:
      privnet:
        ipv4_address: '172.28.1.14'
    depends_on:
      - 'jenkins'
    restart: on-failure:10

