version: '3.1'

volumes:
  prometheus_data: {}
  jenkins_data:
    driver: local

networks:
  back-tier:

services:

  # PROMETHEUS SERVICE
  prometheus:
    image: "prom/prometheus:v2.1.0"
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    networks:
      - back-tier
    restart: always

  # NODE EXPORTER SERVICE
  node-exporter:
    image: "prom/node-exporter"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command: 
      - '--path.procfs=/host/proc' 
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points'
      - '^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)'
    ports:
      - 9100:9100
    networks:
      - back-tier
    restart: always

  # JENKINS SERVICE
  jenkins:
    image: "jenkins/jenkins:lts"
    ports:
      - '8080:8080'
      - '443:8443'
      - '50000:50000'
    volumes:
      - 'jenkins_data:/jenkins_config'

  # JENKINS PYTHON EXPORTER SERVICE
  jenkins-exporter:
    build: ./jenkins-exporter-py
    image: lovoo/jenkins_exporter:latest
    ports:
      - '9118:9118'
    command: ["-j", "http://127.0.0.1:8080", "-p", "9118", "--user", "admin", "--password", "admin"]
