global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.

  external_labels:
      monitor: 'golang-training'

scrape_configs:

  #- job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
  #  scrape_interval: 5s

  #  static_configs:
  #    - targets: ['172.28.1.11:9090']

  - job_name: 'node-exporter'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    static_configs:
      - targets: ['172.28.1.12:9100']

  - job_name: 'jenkins-exporter'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    static_configs:
      - targets: ['172.28.1.14:9200']

